name: Deploy

on:
  workflow_dispatch:   # ✅ این خط ضروری است
  push:                # اختیاری

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip
        run: |
          sudo apt-get install -y unzip
          unzip pakart-website.zip -d ./site
